### ISSUE TITLE
Send messages with image

### ISSUE THREAD

**Issue by deetoomoo** [NathanRLiu/Discord-AutoMessage#2]
Thanks for this awesome package it was really useful! Do you know how I might be able to send images through the discord API as well?

**Comment by NathanRLiu** [comment]
Hey! Thanks for opening this issue. When I first created this repo, I didn't consider that as necessary functionality but I now realize it would be useful so thanks for bringing it to my attention.
If you pull my latest changes, you will see that I have created a new method which can be called to upload files (including media messages) to a specified Discord channel. The method is called "sendFile()", and begins on line 38 of the discord_automessage.py file. The first argument it takes is a Discord ChannelID, the second is the path to the file you want to upload. If it is in the same directory, you won't need to specify the entire path but only the file name. If you need any more help, let me know. Also tell me if you are satisfied with this response so that I can close this issue.

**Comment by deetoomoo** [comment]
Hi Nathan, thanks for this! I actually figured it out and was going to create a pr with a similar change. Thanks for updating! I'm closing this issue
